### ISSUE TITLE
[Question] Is it possible to get the number of packages?

### ISSUE THREAD

**Issue by zardoy** [sindresorhus/npm-user#17]
I want a dynamic badge, which looks like this: [![static badge](https://img.shields.io/static/v1?label=npm%20packages&message=25&color=blue)](https://www.npmjs.com/~sindresorhus) but this is static one. Is there any public API for getting the user's packages count, so can I make the badge dynamic?

**Comment by sindresorhus** [comment]
This package just scrapes the npm profile page and the profile page doesn't show the correct count: https://www.npmjs.com/~sindresorhus You should report that to npm. When they show the correct count, we could scrape that.

As for the badge, you could request one over at https://github.com/badgen/badgen.net

**Comment by zardoy** [comment]
Sorry for misunderstanding, but how did you realise that the profile page doesn't show the correct number?

**Comment by zardoy** [comment]
It seems there is no way of getting the correct count, so I don't care any more. I'm closing this question. Thank you for your help :)
